// Generated by scripts/sync-addresses.mjs from shared/roster.json — do not edit.
// The chain only knows a coin's feed id and ticker; the roster adds its name and
// kind (crypto / meme / stock). Matched by Pyth feed id, then by coinId.

export type RosterKind = "crypto" | "meme" | "stock";

export interface RosterCoin {
  coinId: number;
  ticker: string;
  name: string;
  kind: RosterKind;
  feedId: string;
}

export const ROSTER: readonly RosterCoin[] = [
  {
    "coinId": 0,
    "ticker": "BTC",
    "name": "Bitcoin",
    "kind": "crypto",
    "feedId": "0xe62df6c8b4a85fe1a67db44dc12de5db330f7ac66b72dc658afedf0f4a415b43"
  },
  {
    "coinId": 1,
    "ticker": "ETH",
    "name": "Ethereum",
    "kind": "crypto",
    "feedId": "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace"
  },
  {
    "coinId": 2,
    "ticker": "SOL",
    "name": "Solana",
    "kind": "crypto",
    "feedId": "0xef0d8b6fda2ceba41da15d4095d1da392a0d2f8ed0c6c7bc0f4cfac8c280b56d"
  },
  {
    "coinId": 3,
    "ticker": "MON",
    "name": "Monad",
    "kind": "crypto",
    "feedId": "0x31491744e2dbf6df7fcf4ac0820d18a609b49076d45066d3568424e62f686cd1"
  },
  {
    "coinId": 4,
    "ticker": "BNB",
    "name": "BNB",
    "kind": "crypto",
    "feedId": "0x2f95862b045670cd22bee3114c39763a4a08beeb663b145d283c31d7d1101c4f"
  },
  {
    "coinId": 5,
    "ticker": "XRP",
    "name": "XRP",
    "kind": "crypto",
    "feedId": "0xec5d399846a9209f3fe5881d70aae9268c94339ff9817e8d18ff19fa05eea1c8"
  },
  {
    "coinId": 6,
    "ticker": "DOGE",
    "name": "Dogecoin",
    "kind": "crypto",
    "feedId": "0xdcef50dd0a4cd2dcc17e45df1676dcb336a11a61c69df7a0299b0150c672d25c"
  },
  {
    "coinId": 7,
    "ticker": "AVAX",
    "name": "Avalanche",
    "kind": "crypto",
    "feedId": "0x93da3352f9f1d105fdfe4971cfa80e9dd777bfc5d0f683ebb6e1294b92137bb7"
  },
  {
    "coinId": 8,
    "ticker": "LINK",
    "name": "Chainlink",
    "kind": "crypto",
    "feedId": "0x8ac0c70fff57e9aefdf5edf44b51d62c2d433653cbb2cf5cc06bb115af04d221"
  },
  {
    "coinId": 9,
    "ticker": "SHIB",
    "name": "Shiba Inu",
    "kind": "crypto",
    "feedId": "0xf0d57deca57b3da2fe63a493f4c25925fdfd8edf834b20f93e1f84dbd1504d4a"
  },
  {
    "coinId": 10,
    "ticker": "UNI",
    "name": "Uniswap",
    "kind": "crypto",
    "feedId": "0x78d185a741d07edb3412b09008b7c5cfb9bbbd7d568bf00ba737b456ba171501"
  },
  {
    "coinId": 11,
    "ticker": "ADA",
    "name": "Cardano",
    "kind": "crypto",
    "feedId": "0x2a01deaec9e51a579277b34b122399984d0bbf57e2458a7e42fecd2829867a0d"
  },
  {
    "coinId": 12,
    "ticker": "BONK",
    "name": "Bonk",
    "kind": "meme",
    "feedId": "0x72b021217ca3fe68922a19aaf990109cb9d84e9ad004b4d2025ad6f529314419"
  },
  {
    "coinId": 13,
    "ticker": "WIF",
    "name": "dogwifhat",
    "kind": "meme",
    "feedId": "0x4ca4beeca86f0d164160323817a4e42b10010a724c2217c6ee41b54cd4cc61fc"
  },
  {
    "coinId": 14,
    "ticker": "POPCAT",
    "name": "Popcat",
    "kind": "meme",
    "feedId": "0xb9312a7ee50e189ef045aa3c7842e099b061bd9bdc99ac645956c3b660dc8cce"
  },
  {
    "coinId": 15,
    "ticker": "PNUT",
    "name": "Peanut the Squirrel",
    "kind": "meme",
    "feedId": "0x116da895807f81f6b5c5f01b109376e7f6834dc8b51365ab7cdfa66634340e54"
  },
  {
    "coinId": 16,
    "ticker": "GOAT",
    "name": "Goatseus Maximus",
    "kind": "meme",
    "feedId": "0xf7731dc812590214d3eb4343bfb13d1b4cfa9b1d4e020644b5d5d8e07d60c66c"
  },
  {
    "coinId": 17,
    "ticker": "MEW",
    "name": "cat in a dogs world",
    "kind": "meme",
    "feedId": "0x514aed52ca5294177f20187ae883cec4a018619772ddce41efcc36a6448f5d5d"
  },
  {
    "coinId": 18,
    "ticker": "PEPE",
    "name": "Pepe",
    "kind": "meme",
    "feedId": "0xd69731a2e74ac1ce884fc3890f7ee324b6deb66147055249568869ed700882e4"
  },
  {
    "coinId": 19,
    "ticker": "BRETT",
    "name": "Brett",
    "kind": "meme",
    "feedId": "0x9b5729efe3d68e537cdcb2ca70444dea5f06e1660b562632609757076d0b9448"
  },
  {
    "coinId": 20,
    "ticker": "MOG",
    "name": "Mog",
    "kind": "meme",
    "feedId": "0x17894b9fff49cd07efeab94a0d02db16f158efe04e0dee1db6af5f069082ce83"
  },
  {
    "coinId": 21,
    "ticker": "MOODENG",
    "name": "Moo Deng",
    "kind": "meme",
    "feedId": "0xffff73128917a90950cd0473fd2551d7cd274fd5a6cc45641881bbcc6ee73417"
  },
  {
    "coinId": 22,
    "ticker": "CHILLGUY",
    "name": "Chill Guy",
    "kind": "meme",
    "feedId": "0xd98869edbb4a0d2803dc1054405bceb1ddc546bfc9a3d0e31bb0e0448e6181e1"
  },
  {
    "coinId": 23,
    "ticker": "BOME",
    "name": "Book of Meme",
    "kind": "meme",
    "feedId": "0x30e4780570973e438fdb3f1b7ad22618b2fc7333b65c7853a7ca144c39052f7a"
  },
  {
    "coinId": 24,
    "ticker": "AAPL",
    "name": "Apple",
    "kind": "stock",
    "feedId": "0x49f6b65cb1de6b10eaf75e7c03ca029c306d0357e91b5311b175084a5ad55688"
  },
  {
    "coinId": 25,
    "ticker": "TSLA",
    "name": "Tesla",
    "kind": "stock",
    "feedId": "0x16dad506d7db8da01c87581c87ca897a012a153557d4d578c3b9c9e1bc0632f1"
  },
  {
    "coinId": 26,
    "ticker": "NVDA",
    "name": "Nvidia",
    "kind": "stock",
    "feedId": "0xb1073854ed24cbc755dc527418f52b7d271f6cc967bbf8d8129112b18860a593"
  },
  {
    "coinId": 27,
    "ticker": "MSFT",
    "name": "Microsoft",
    "kind": "stock",
    "feedId": "0xd0ca23c1cc005e004ccf1db5bf76aeb6a49218f43dac3d4b275e92de12ded4d1"
  },
  {
    "coinId": 28,
    "ticker": "GOOGL",
    "name": "Alphabet",
    "kind": "stock",
    "feedId": "0x5a48c03e9b9cb337801073ed9d166817473697efff0d138874e0f6a33d6d5aa6"
  },
  {
    "coinId": 29,
    "ticker": "AMZN",
    "name": "Amazon",
    "kind": "stock",
    "feedId": "0xb5d0e0fa58a1f8b81498ae670ce93c872d14434b72c364885d4fa1b257cbb07a"
  },
  {
    "coinId": 30,
    "ticker": "META",
    "name": "Meta",
    "kind": "stock",
    "feedId": "0x78a3e3b8e676a8f73c439f5d749737034b139bbbe899ba5775216fba596607fe"
  },
  {
    "coinId": 31,
    "ticker": "NFLX",
    "name": "Netflix",
    "kind": "stock",
    "feedId": "0x8376cfd7ca8bcdf372ced05307b24dced1f15b1afafdeff715664598f15a3dd2"
  },
  {
    "coinId": 32,
    "ticker": "COIN",
    "name": "Coinbase",
    "kind": "stock",
    "feedId": "0xfee33f2a978bf32dd6b662b65ba8083c6773b494f8401194ec1870c640860245"
  },
  {
    "coinId": 33,
    "ticker": "HOOD",
    "name": "Robinhood",
    "kind": "stock",
    "feedId": "0x306736a4035846ba15a3496eed57225b64cc19230a50d14f3ed20fd7219b7849"
  },
  {
    "coinId": 34,
    "ticker": "MSTR",
    "name": "MicroStrategy",
    "kind": "stock",
    "feedId": "0xe1e80251e5f5184f2195008382538e847fafc36f751896889dd3d1b1f6111f09"
  },
  {
    "coinId": 35,
    "ticker": "SPY",
    "name": "S and P 500",
    "kind": "stock",
    "feedId": "0x19e09bb805456ada3979a7d1cbb4b6d63babc3a0f8e8a9509f68afa5c4c11cd5"
  }
];
