#!/usr/bin/env bun
/**
 * Writes cre/market-meta/roster.ts from shared/roster.json.
 *
 * The workflow runs as WASM inside the DON and cannot read files, so the
 * roster has to be compiled in. Generating it (rather than hand-copying)
 * keeps the coin ids the workflow reports identical to the ones the game
 * clients and contracts use. `market-meta/roster.test.ts` fails if the two
 * drift, so re-run this whenever shared/roster.json changes:
 *
 *   cd cre/market-meta && bun run gen:roster
 */
// Bun APIs only (no node:* imports): the CRE SDK's type restrictions apply to
// every file typechecked alongside the workflow, and they ban Node built-ins.

type SharedCoin = {
	coinId: number
	ticker: string
	kind: 'crypto' | 'meme' | 'stock'
	feedId: string
	coingeckoId?: string
}

const creRoot = `${import.meta.dir}/..`
const source = `${creRoot}/../shared/roster.json`
const target = `${creRoot}/market-meta/roster.ts`

const shared = (await Bun.file(source).json()) as { chainId: number; coins: SharedCoin[] }

const seen = new Set<number>()
const rows = shared.coins
	.map((c) => {
		if (!Number.isInteger(c.coinId) || c.coinId < 0 || c.coinId > 0xffff) {
			throw new Error(`coinId ${c.coinId} (${c.ticker}) does not fit uint16`)
		}
		if (seen.has(c.coinId)) throw new Error(`duplicate coinId ${c.coinId}`)
		seen.add(c.coinId)
		if (c.kind !== 'stock' && !c.coingeckoId) {
			throw new Error(`${c.ticker} is ${c.kind} but has no coingeckoId`)
		}
		if (!/^0x[0-9a-f]{64}$/i.test(c.feedId)) throw new Error(`${c.ticker} has a malformed Pyth feedId`)
		return {
			coinId: c.coinId,
			ticker: c.ticker,
			kind: c.kind,
			coingeckoId: c.kind === 'stock' ? null : (c.coingeckoId as string),
			feedId: c.feedId.toLowerCase(),
		}
	})
	.sort((a, b) => a.coinId - b.coinId)

const body = rows
	.map(
		(r) =>
			`\t{ coinId: ${r.coinId}, ticker: ${JSON.stringify(r.ticker)}, kind: ${JSON.stringify(r.kind)}, coingeckoId: ${JSON.stringify(r.coingeckoId)}, feedId: ${JSON.stringify(r.feedId)} },`,
	)
	.join('\n')

const out = `// GENERATED by cre/scripts/gen-roster.ts from shared/roster.json — do not edit.
// Re-run \`bun run gen:roster\` (in cre/market-meta) after changing the roster.

export type CoinKind = 'crypto' | 'meme' | 'stock'

export type RosterCoin = {
	/** uint16 id shared by the contracts, the game clients and this workflow. */
	readonly coinId: number
	readonly ticker: string
	readonly kind: CoinKind
	/** CoinGecko id for crypto/meme coins; null for stocks. */
	readonly coingeckoId: string | null
	/** Pyth price feed id (lowercase, 0x-prefixed). */
	readonly feedId: string
}

export const ROSTER_CHAIN_ID = ${shared.chainId}

export const ROSTER: readonly RosterCoin[] = [
${body}
]
`

await Bun.write(target, out)
console.log(`wrote cre/market-meta/roster.ts (${rows.length} coins)`)
